CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS unidade_saude CASCADE;

CREATE TABLE unidade_saude (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(100) NOT NULL,
    cnes VARCHAR(20) NOT NULL UNIQUE
);
