definitions:
  request.LoginRequest:
    properties:
      identificador:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
  response.LoginResponse:
    properties:
      message:
        type: string
      redirect:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/response.UserResponse'
    type: object
  response.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Credenciais de login
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginResponse'
      summary: Login de usuário
      tags:
      - auth
swagger: "2.0"
